<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="NoSQLsecurity" nsURI="https://gsya.esi.uclm.es/NoSQLsecurity"
    nsPrefix="NoSQLsecurity">
  <eClassifiers xsi:type="ecore:EClass" name="Database">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
        eType="#//Role"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="users" upperBound="-1"
        eType="#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//SecurityRule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Role"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="root" eType="#//Role"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//SecurityRule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pass" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" lowerBound="1" upperBound="-1"
        eType="#//Role"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityRule" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sign" lowerBound="1" eType="#//SignType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" lowerBound="1" upperBound="-1"
        eType="#//Role"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="privileges" lowerBound="1"
        upperBound="-1" eType="#//Privilege"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityRuleField" eSuperTypes="#//SecurityRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" lowerBound="1"
        upperBound="-1" eType="ecore:EClass NoSQLgraph.ecore#//Field"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityRuleElement" eSuperTypes="#//SecurityRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" lowerBound="1"
        upperBound="-1" eType="ecore:EClass NoSQLgraph.ecore#//Element"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Privilege">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="securityAction" eType="#//SecurityAction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="HideInstance" eSuperTypes="#//SecurityAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="HideValue" eSuperTypes="#//SecurityAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="HideAllValues" eSuperTypes="#//SecurityAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="HideField" eSuperTypes="#//SecurityAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Create" eSuperTypes="#//Privilege"/>
  <eClassifiers xsi:type="ecore:EClass" name="Read" eSuperTypes="#//Privilege"/>
  <eClassifiers xsi:type="ecore:EClass" name="Update" eSuperTypes="#//Privilege"/>
  <eClassifiers xsi:type="ecore:EClass" name="Delete" eSuperTypes="#//Privilege"/>
  <eClassifiers xsi:type="ecore:EEnum" name="SignType">
    <eLiterals name="positive" literal="+"/>
    <eLiterals name="negative" value="1" literal="-"/>
  </eClassifiers>
</ecore:EPackage>
